# Generated by Django 3.2 on 2022-09-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0028_auto_20220925_1321"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainZipcode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kommune"
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Postnummer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hovedpostnummer",
                "verbose_name_plural": "Hovedpostnumre",
            },
        ),
    ]
