# Generated by Django 3.2 on 2022-09-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0029_mainzipcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="family",
            old_name="anonymized",
            new_name="anonymized_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="anonymized",
            new_name="anonymized_at",
        ),
    ]
