# Generated by Django 3.2 on 2022-09-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0030_auto_20220925_1416"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["added_at"],
                "permissions": (
                    (
                        "view_full_address",
                        "Can view persons full address + phonenumber + email",
                    ),
                    ("view_all_persons", "Can view persons not related to department"),
                ),
                "verbose_name": "Person",
                "verbose_name_plural": "Personer",
            },
        ),
        migrations.RenameField(
            model_name="family",
            old_name="confirmed_dtm",
            new_name="confirmed_at",
        ),
        migrations.RenameField(
            model_name="family",
            old_name="last_visit_dtm",
            new_name="last_visit_at",
        ),
        migrations.RenameField(
            model_name="family",
            old_name="updated_dtm",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="accepted_dtm",
            new_name="accepted_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="added",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="cancelled_dtm",
            new_name="cancelled_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="confirmed_dtm",
            new_name="confirmed_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="refunded_dtm",
            new_name="refunded_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="rejected_dtm",
            new_name="rejected_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="added",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="updated_dtm",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="person",
            name="deleted_dtm",
        ),
    ]
